/**
 * Unit tests for the LOCAL AI provider path in useAiOperations.
 *
 * The defining property of the local provider is zero egress: it must never
 * trigger the per-send cloud confirmation gate, and it must provision the
 * bundled server (download/start) before running. These tests pin both.
 */
import { describe, it, expect, beforeEach, vi } from 'vitest'
import { renderHook, act } from '@testing-library/react'
import { useAiOperations } from './useAiOperations'
import { createMockInstance } from '@/test/fixtures/dicomData'

// Shared spies/objects, defined before vi.mock factories run (avoids TDZ).
const { confirmAiSend, ensureLocalServer, localDetector } = vi.hoisted(() => {
  const localDetector = {
    detectVertebrae: vi.fn().mockResolvedValue({
      annotations: [
        {
          id: 'ann1',
          type: 'marker' as const,
          position: { x: 10, y: 20 },
          label: 'L1',
          severity: 'normal' as const,
          sopInstanceUID: 'test-instance-uid',
          autoGenerated: true,
        },
      ],
      confidence: 0.8,
      processingTimeMs: 42,
    }),
    analyzeImage: vi.fn().mockResolvedValue({
      analysis: { findings: 'Local findings' },
      processingTimeMs: 99,
    }),
    isConfigured: vi.fn(() => true),
    setApiKey: vi.fn(),
  }
  return {
    confirmAiSend: vi.fn(async () => true),
    ensureLocalServer: vi.fn(async () => ({ running: true, model: 'medgemma-4b-it', port: 8080 })),
    localDetector,
  }
})

// Settings: local provider selected, with a preconfigured model + port.
vi.mock('@/stores/settingsStore', () => ({
  useSettingsStore: {
    getState: () => ({
      aiEnabled: true,
      aiProvider: 'local',
      localModel: 'medgemma-4b-it',
      localPort: 8080,
      aiApiKey: '',
      geminiApiKey: '',
      openaiApiKey: '',
      aiResponseLanguage: 'English',
    }),
  },
}))

vi.mock('@/lib/utils/platform', () => ({ isTauri: () => true }))

// The per-send egress gate — must NOT be called for the local provider.
vi.mock('@/lib/ai/ai-send-confirm', () => ({ confirmAiSend }))

// Server provisioning bridge — assert it runs before inference.
vi.mock('@/lib/ai/localServer', () => ({ ensureLocalServer }))

vi.mock('@/lib/ai/mockVertebralDetector', () => ({ mockDetector: { isConfigured: () => true } }))
vi.mock('@/lib/ai/aiDetectorManager', () => ({
  initDetector: vi.fn(async () => localDetector),
  getApiKeyForProvider: vi.fn(() => ''),
}))

describe('useAiOperations — local provider (zero egress)', () => {
  const options = {
    currentInstance: createMockInstance(),
    currentStudy: {
      studyInstanceUID: 'study-uid',
      patientName: 'Test',
      patientID: '1',
      studyDate: '20240101',
      studyDescription: 'Test',
      series: [],
    },
    isDetecting: false,
    isAnalyzing: false,
    setDetecting: vi.fn(),
    setAnalyzing: vi.fn(),
    addAnnotations: vi.fn(),
    deleteAnnotationsForInstance: vi.fn(),
    addAnalysis: vi.fn(),
    handleError: vi.fn(),
  }

  beforeEach(() => vi.clearAllMocks())

  it('detection never opens the cloud send-confirmation dialog', async () => {
    const { result } = renderHook(() => useAiOperations(options))
    await act(async () => {
      await result.current.handleAiDetection()
    })

    expect(confirmAiSend).not.toHaveBeenCalled()
    expect(ensureLocalServer).toHaveBeenCalledWith('medgemma-4b-it', 8080, expect.any(Function))
    expect(localDetector.detectVertebrae).toHaveBeenCalled()
    expect(options.addAnnotations).toHaveBeenCalled()
  })

  it('analysis never opens the cloud send-confirmation dialog', async () => {
    const { result } = renderHook(() => useAiOperations(options))
    await act(async () => {
      await result.current.handleAiAnalysis()
    })

    expect(confirmAiSend).not.toHaveBeenCalled()
    expect(ensureLocalServer).toHaveBeenCalledWith('medgemma-4b-it', 8080, expect.any(Function))
    expect(localDetector.analyzeImage).toHaveBeenCalled()
    expect(options.addAnalysis).toHaveBeenCalledWith(expect.objectContaining({ studyInstanceUID: 'study-uid' }))
  })

  it('provisions the server BEFORE running inference', async () => {
    const order: string[] = []
    ensureLocalServer.mockImplementationOnce(async () => {
      order.push('ensure')
      return { running: true, model: 'medgemma-4b-it', port: 8080 }
    })
    localDetector.detectVertebrae.mockImplementationOnce(async () => {
      order.push('detect')
      return { annotations: [], confidence: 0, processingTimeMs: 1 }
    })

    const { result } = renderHook(() => useAiOperations(options))
    await act(async () => {
      await result.current.handleAiDetection()
    })

    expect(order).toEqual(['ensure', 'detect'])
  })
})
