import { useState, useCallback } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { useAiAnalysisStore } from '@/stores/aiAnalysisStore'
import { useStudyStore } from '@/stores/studyStore'

export function AiAnalysisModal() {
  const isModalVisible = useAiAnalysisStore((state) => state.isModalVisible)
  const selectedAnalysisId = useAiAnalysisStore((state) => state.selectedAnalysisId)
  const analyses = useAiAnalysisStore((state) => state.analyses)
  const hideModal = useAiAnalysisStore((state) => state.hideModal)
  const showModal = useAiAnalysisStore((state) => state.showModal)
  const deleteAnalysis = useAiAnalysisStore((state) => state.deleteAnalysis)
  const currentInstance = useStudyStore((state) => state.currentInstance)

  const [viewMode, setViewMode] = useState<'rendered' | 'raw'>('rendered')
  const [copied, setCopied] = useState(false)

  // Get the analysis for the current image
  const currentAnalysis = currentInstance
    ? analyses.find((a) => a.sopInstanceUID === currentInstance.sopInstanceUID)
    : null

  const handleDelete = () => {
    if (!currentAnalysis) return
    if (confirm('Are you sure you want to delete this AI analysis?')) {
      deleteAnalysis(currentAnalysis.id)
    }
  }

  const handleMinimizedClick = () => {
    if (currentAnalysis) {
      showModal(currentAnalysis.id)
    }
  }

  const handleCopy = useCallback(async () => {
    if (!currentAnalysis) return
    try {
      await navigator.clipboard.writeText(currentAnalysis.findings)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy to clipboard:', err)
    }
  }, [currentAnalysis])

  const handlePrint = useCallback(() => {
    if (!currentAnalysis) return

    const printWindow = window.open('', '_blank')
    if (!printWindow) return

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>AI Radiology Analysis</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
              max-width: 800px;
              margin: 0 auto;
              padding: 40px 20px;
              color: #1a1a1a;
              line-height: 1.6;
            }
            h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
            h2 { font-size: 1.25rem; margin-top: 1.5rem; }
            h3 { font-size: 1.1rem; margin-top: 1.25rem; }
            p { margin: 0.5rem 0; }
            ul, ol { padding-left: 1.5rem; }
            li { margin: 0.25rem 0; }
            table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
            th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
            th { background: #f5f5f5; }
            hr { border: none; border-top: 1px solid #ddd; margin: 1.5rem 0; }
            code { background: #f5f5f5; padding: 2px 4px; border-radius: 3px; font-size: 0.9em; }
            pre { background: #f5f5f5; padding: 12px; border-radius: 4px; overflow-x: auto; }
            pre code { background: none; padding: 0; }
            .meta { color: #666; font-size: 0.85rem; margin-bottom: 2rem; border-bottom: 1px solid #ddd; padding-bottom: 1rem; }
            @media print {
              body { padding: 0; }
            }
          </style>
        </head>
        <body>
          <h1>AI Radiology Analysis</h1>
          <div class="meta">
            Generated by ${currentAnalysis.createdBy} &middot; ${new Date(currentAnalysis.createdAt).toLocaleString()}
          </div>
          <div id="content"></div>
          <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"><\/script>
          <script>
            document.getElementById('content').innerHTML = marked.parse(${JSON.stringify(currentAnalysis.findings)});
            setTimeout(() => { window.print(); window.close(); }, 500);
          <\/script>
        </body>
      </html>
    `)
    printWindow.document.close()
  }, [currentAnalysis])

  // Show minimized icon if there's an analysis but modal is hidden
  if (!isModalVisible && currentAnalysis) {
    return (
      <button
        onClick={handleMinimizedClick}
        title="View AI analysis"
        className="absolute bottom-[6.25rem] left-4 bg-[#1a1a1a]/90 backdrop-blur-sm border border-[#2a2a2a] text-gray-300 hover:bg-[#2a2a2a] hover:text-white p-2.5 rounded-lg shadow-lg transition-colors z-30"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 20 20"
          fill="currentColor"
          className="w-4 h-4"
        >
          <path
            fillRule="evenodd"
            d="M4.5 2A1.5 1.5 0 003 3.5v13A1.5 1.5 0 004.5 18h11a1.5 1.5 0 001.5-1.5V7.621a1.5 1.5 0 00-.44-1.06l-4.12-4.122A1.5 1.5 0 0011.378 2H4.5zm2.25 8.5a.75.75 0 000 1.5h6.5a.75.75 0 000-1.5h-6.5zm0 3a.75.75 0 000 1.5h6.5a.75.75 0 000-1.5h-6.5z"
            clipRule="evenodd"
          />
        </svg>
      </button>
    )
  }

  if (!isModalVisible || !selectedAnalysisId || !currentAnalysis) return null

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-[#1a1a1a] border border-[#2a2a2a] rounded-lg shadow-2xl max-w-3xl w-full max-h-[80vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-[#2a2a2a]">
          <div className="flex items-center gap-2">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
              fill="currentColor"
              className="w-5 h-5 text-blue-500"
            >
              <path d="M15.98 1.804a1 1 0 00-1.96 0l-.24 1.192a1 1 0 01-.784.785l-1.192.238a1 1 0 000 1.962l1.192.238a1 1 0 01.785.785l.238 1.192a1 1 0 001.962 0l.238-1.192a1 1 0 01.785-.785l1.192-.238a1 1 0 000-1.962l-1.192-.238a1 1 0 01-.785-.785l-.238-1.192zM6.949 5.684a1 1 0 00-1.898 0l-.683 2.051a1 1 0 01-.633.633l-2.051.683a1 1 0 000 1.898l2.051.684a1 1 0 01.633.632l.683 2.051a1 1 0 001.898 0l.683-2.051a1 1 0 01.633-.633l2.051-.683a1 1 0 000-1.898l-2.051-.683a1 1 0 01-.633-.633L6.95 5.684zM13.949 13.684a1 1 0 00-1.898 0l-.184.551a1 1 0 01-.632.633l-.551.183a1 1 0 000 1.898l.551.183a1 1 0 01.633.633l.183.551a1 1 0 001.898 0l.184-.551a1 1 0 01.632-.633l.551-.183a1 1 0 000-1.898l-.551-.184a1 1 0 01-.633-.632l-.183-.551z" />
            </svg>
            <h2 className="text-lg font-semibold text-white">AI Radiology Analysis</h2>
            {/* View mode toggle */}
            <div className="flex ml-3 bg-[#0a0a0a] rounded overflow-hidden border border-[#333]">
              <button
                onClick={() => setViewMode('rendered')}
                className={`px-2.5 py-1 text-xs font-medium transition-colors ${
                  viewMode === 'rendered'
                    ? 'bg-blue-600 text-white'
                    : 'text-gray-400 hover:text-gray-200'
                }`}
              >
                Rendered
              </button>
              <button
                onClick={() => setViewMode('raw')}
                className={`px-2.5 py-1 text-xs font-medium transition-colors ${
                  viewMode === 'raw'
                    ? 'bg-blue-600 text-white'
                    : 'text-gray-400 hover:text-gray-200'
                }`}
              >
                Raw
              </button>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {/* Print button */}
            <button
              onClick={handlePrint}
              title="Print analysis"
              className="p-1.5 text-gray-400 hover:text-blue-400 hover:bg-[#2a2a2a] rounded transition-colors"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
                className="w-4 h-4"
              >
                <path
                  fillRule="evenodd"
                  d="M5 2.75C5 1.784 5.784 1 6.75 1h6.5c.966 0 1.75.784 1.75 1.75v3.552c.377.046.752.097 1.126.153A2.212 2.212 0 0118 8.653v4.097A2.25 2.25 0 0115.75 15h-.55a.75.75 0 000-1.5h.55a.75.75 0 00.75-.75V8.653a.712.712 0 00-.615-.711 47.965 47.965 0 00-11.77 0 .712.712 0 00-.615.711v4.097c0 .414.336.75.75.75h.55a.75.75 0 000 1.5h-.55A2.25 2.25 0 012 12.75V8.653c0-1.082.775-2.034 1.874-2.198.374-.056.749-.107 1.126-.153V2.75zm1.5 0v3.36a49.323 49.323 0 017 0V2.75a.25.25 0 00-.25-.25h-6.5a.25.25 0 00-.25.25zM14 13a.75.75 0 00-.75-.75h-6.5a.75.75 0 00-.75.75v4.25c0 .414.336.75.75.75h6.5a.75.75 0 00.75-.75V13zm-1.5.75v2.75h-5v-2.75h5z"
                  clipRule="evenodd"
                />
              </svg>
            </button>
            {/* Copy button */}
            <button
              onClick={handleCopy}
              title={copied ? 'Copied!' : 'Copy to clipboard'}
              className={`p-1.5 hover:bg-[#2a2a2a] rounded transition-colors ${
                copied ? 'text-green-400' : 'text-gray-400 hover:text-blue-400'
              }`}
            >
              {copied ? (
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                  className="w-4 h-4"
                >
                  <path
                    fillRule="evenodd"
                    d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z"
                    clipRule="evenodd"
                  />
                </svg>
              ) : (
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                  className="w-4 h-4"
                >
                  <path d="M7 3.5A1.5 1.5 0 018.5 2h3.879a1.5 1.5 0 011.06.44l3.122 3.12A1.5 1.5 0 0117 6.622V12.5a1.5 1.5 0 01-1.5 1.5h-1v-3.379a3 3 0 00-.879-2.121L10.5 5.379A3 3 0 008.379 4.5H7v-1z" />
                  <path d="M4.5 6A1.5 1.5 0 003 7.5v9A1.5 1.5 0 004.5 18h7a1.5 1.5 0 001.5-1.5v-5.879a1.5 1.5 0 00-.44-1.06L9.44 6.439A1.5 1.5 0 008.378 6H4.5z" />
                </svg>
              )}
            </button>
            {/* Delete button */}
            <button
              onClick={handleDelete}
              title="Delete analysis"
              className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-[#2a2a2a] rounded transition-colors"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
                className="w-4 h-4"
              >
                <path
                  fillRule="evenodd"
                  d="M8.75 1A2.75 2.75 0 006 3.75v.443c-.795.077-1.584.176-2.365.298a.75.75 0 10.23 1.482l.149-.022.841 10.518A2.75 2.75 0 007.596 19h4.807a2.75 2.75 0 002.742-2.53l.841-10.52.149.023a.75.75 0 00.23-1.482A41.03 41.03 0 0014 4.193V3.75A2.75 2.75 0 0011.25 1h-2.5zM10 4c.84 0 1.673.025 2.5.075V3.75c0-.69-.56-1.25-1.25-1.25h-2.5c-.69 0-1.25.56-1.25 1.25v.325C8.327 4.025 9.16 4 10 4zM8.58 7.72a.75.75 0 00-1.5.06l.3 7.5a.75.75 0 101.5-.06l-.3-7.5zm4.34.06a.75.75 0 10-1.5-.06l-.3 7.5a.75.75 0 101.5.06l.3-7.5z"
                  clipRule="evenodd"
                />
              </svg>
            </button>
            {/* Close button */}
            <button
              onClick={hideModal}
              title="Close"
              className="p-1.5 text-gray-400 hover:text-white hover:bg-[#2a2a2a] rounded transition-colors"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
                className="w-4 h-4"
              >
                <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
              </svg>
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {viewMode === 'rendered' ? (
            <div className="prose prose-invert prose-sm max-w-none prose-headings:text-gray-100 prose-p:text-gray-300 prose-strong:text-gray-200 prose-li:text-gray-300 prose-a:text-blue-400 prose-code:text-gray-200 prose-pre:bg-[#0a0a0a] prose-hr:border-[#333]">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {currentAnalysis.findings}
              </ReactMarkdown>
            </div>
          ) : (
            <div className="prose prose-invert prose-sm max-w-none">
              <div className="whitespace-pre-wrap text-gray-300 leading-relaxed font-mono text-xs">
                {currentAnalysis.findings}
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-[#2a2a2a] text-xs text-gray-500 flex items-center justify-between">
          <div>
            Generated by <span className="text-gray-400 font-medium">{currentAnalysis.createdBy}</span>
          </div>
          <div>
            {new Date(currentAnalysis.createdAt).toLocaleString()}
          </div>
        </div>
      </div>
    </div>
  )
}
