/* eslint-disable react-hooks/exhaustive-deps */
import { useState, useCallback } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { jsPDF } from 'jspdf'
import { FileText, Printer, Copy, Check, Trash2 } from 'lucide-react'
import { Modal } from '@/components/ui/Modal'
import { Tooltip, Button, SegmentedControl } from '@/components/ui'
import { useAiAnalysisStore } from '@/stores/aiAnalysisStore'
import { useStudyStore } from '@/stores/studyStore'
import { useSettingsStore } from '@/stores/settingsStore'
import { themeClasses } from '@/lib/utils'
import { useErrorHandler } from '@/hooks/useErrorHandler'
import { isTauri } from '@/lib/utils/platform'
import { confirmDialog } from '@/lib/ui/confirm'

export function AiAnalysisModal() {
  const isModalVisible = useAiAnalysisStore((state) => state.isModalVisible)
  const selectedAnalysisId = useAiAnalysisStore((state) => state.selectedAnalysisId)
  const analyses = useAiAnalysisStore((state) => state.analyses)
  const hideModal = useAiAnalysisStore((state) => state.hideModal)
  const deleteAnalysis = useAiAnalysisStore((state) => state.deleteAnalysis)
  const currentInstance = useStudyStore((state) => state.currentInstance)

  const [viewMode, setViewMode] = useState<'rendered' | 'raw'>('rendered')
  const [copied, setCopied] = useState(false)
  const theme = useSettingsStore((state) => state.theme)

  const { handleError } = useErrorHandler()

  // Get the analysis for the current image
  const currentAnalysis = currentInstance
    ? analyses.find((a) => a.sopInstanceUID === currentInstance.sopInstanceUID)
    : null

  const handleDelete = useCallback(async (event?: React.MouseEvent) => {
    // Prevent any default behavior or event bubbling
    if (event) {
      event.preventDefault()
      event.stopPropagation()
    }

    if (!currentAnalysis) return

    // Store the ID before showing confirmation
    const analysisIdToDelete = currentAnalysis.id

    // Themed, always-async confirm (replaces native window.confirm, which
    // behaved differently on web vs. the Tauri desktop build).
    const confirmed = await confirmDialog({
      title: 'Delete AI analysis',
      message: 'Are you sure you want to delete this AI analysis?',
      confirmLabel: 'Delete',
    })

    if (!confirmed) {
      // User cancelled - do nothing
      return
    }

    // Only reached if user clicked OK
    deleteAnalysis(analysisIdToDelete)
    hideModal()
  }, [currentAnalysis, deleteAnalysis, hideModal])


  const handleCopy = useCallback(async () => {
    if (!currentAnalysis) return
    try {
      await navigator.clipboard.writeText(currentAnalysis.findings)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy to clipboard:', err)
    }
  }, [currentAnalysis])

  const handlePrint = useCallback(async () => {
    if (!currentAnalysis) return

    console.log('Generating PDF...', { isTauri: isTauri() })

    try {
      // Create PDF document
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      })

      // PDF dimensions
      const pageWidth = pdf.internal.pageSize.getWidth()
      const pageHeight = pdf.internal.pageSize.getHeight()
      const margin = 20
      const maxWidth = pageWidth - (margin * 2)
      let yPos = margin

      // Helper to add text with word wrapping
      const addText = (text: string, fontSize: number, fontStyle: 'normal' | 'bold' = 'normal', leftMargin = 0) => {
        pdf.setFontSize(fontSize)
        pdf.setFont('helvetica', fontStyle)
        const lines = pdf.splitTextToSize(text, maxWidth - leftMargin)

        lines.forEach((line: string) => {
          // Check if we need a new page
          if (yPos > pageHeight - margin) {
            pdf.addPage()
            yPos = margin
          }
          pdf.text(line, margin + leftMargin, yPos)
          yPos += fontSize * 0.5
        })
        yPos += 3 // Extra spacing after paragraph
      }

      // Add title
      pdf.setFontSize(20)
      pdf.setFont('helvetica', 'bold')
      pdf.text('AI Radiology Analysis', margin, yPos)
      yPos += 12

      // Add metadata
      pdf.setFontSize(9)
      pdf.setFont('helvetica', 'normal')
      pdf.setTextColor(100, 100, 100)
      pdf.text(`Generated by ${currentAnalysis.createdBy} • ${new Date(currentAnalysis.createdAt).toLocaleString()}`, margin, yPos)
      yPos += 10
      pdf.setTextColor(0, 0, 0)

      // Add line separator
      pdf.setDrawColor(200, 200, 200)
      pdf.line(margin, yPos, pageWidth - margin, yPos)
      yPos += 8

      // Parse and add content based on view mode
      if (viewMode === 'raw') {
        // Raw markdown - just add as monospace text
        pdf.setFont('courier', 'normal')
        pdf.setFontSize(9)
        const lines = currentAnalysis.findings.split('\n')
        lines.forEach(line => {
          if (yPos > pageHeight - margin) {
            pdf.addPage()
            yPos = margin
          }
          pdf.text(line || ' ', margin, yPos)
          yPos += 4
        })
      } else {
        // Rendered view - parse markdown into formatted text
        const lines = currentAnalysis.findings.split('\n')

        for (const line of lines) {
          if (!line.trim()) {
            yPos += 3
            continue
          }

          // Headers
          if (line.startsWith('# ')) {
            yPos += 5
            addText(line.substring(2), 16, 'bold')
          } else if (line.startsWith('## ')) {
            yPos += 4
            addText(line.substring(3), 14, 'bold')
          } else if (line.startsWith('### ')) {
            yPos += 3
            addText(line.substring(4), 12, 'bold')
          } else if (line.startsWith('#### ')) {
            yPos += 2
            addText(line.substring(5), 11, 'bold')
          }
          // Bullet points
          else if (line.match(/^[*\-+]\s/)) {
            const text = '• ' + line.substring(2)
            addText(text, 10, 'normal', 5)
          }
          // Numbered lists
          else if (line.match(/^\d+\.\s/)) {
            addText(line, 10, 'normal', 5)
          }
          // Bold text (simple parsing)
          else if (line.includes('**')) {
            const text = line.replace(/\*\*(.*?)\*\*/g, '$1')
            addText(text, 10, 'bold')
          }
          // Regular paragraph
          else {
            addText(line, 10, 'normal')
          }
        }
      }

      // Generate PDF
      const pdfBlob = pdf.output('blob')
      const fileName = `AI_Analysis_${new Date().toISOString().slice(0, 10)}.pdf`

      if (isTauri()) {
        // In Tauri, save to Downloads directory
        const { writeFile } = await import('@tauri-apps/plugin-fs')
        const { save } = await import('@tauri-apps/plugin-dialog')

        // Convert blob to Uint8Array
        const arrayBuffer = await pdfBlob.arrayBuffer()
        const uint8Array = new Uint8Array(arrayBuffer)

        // Let user choose where to save the PDF
        const filePath = await save({
          defaultPath: fileName,
          filters: [{
            name: 'PDF',
            extensions: ['pdf']
          }]
        })

        if (filePath) {
          await writeFile(filePath, uint8Array)
          handleError(`PDF saved to: ${filePath}`, 'PDF Export', 'success')
        }
      } else {
        // In browser, open PDF in new tab
        const pdfUrl = URL.createObjectURL(pdfBlob)
        const newWindow = window.open(pdfUrl, '_blank')

        if (!newWindow) {
          // Fallback: download the PDF
          const link = document.createElement('a')
          link.href = pdfUrl
          link.download = fileName
          link.click()
          URL.revokeObjectURL(pdfUrl)
        } else {
          // Clean up URL after a delay
          setTimeout(() => URL.revokeObjectURL(pdfUrl), 1000)
        }
      }
    } catch (err) {
      handleError(err as Error, 'PDF Export', 'error')
    }
  }, [currentAnalysis, viewMode])

  // Don't render anything if modal is not visible
  // Analysis indicator is now shown only in the thumbnail strip
  if (!isModalVisible || !selectedAnalysisId || !currentAnalysis) return null

  return (
    <Modal
      show={isModalVisible}
      onClose={hideModal}
      title="AI Radiology Analysis"
      icon={<FileText />}
      headerLeftActions={
        <div className="ml-3">
          <SegmentedControl
            value={viewMode}
            onChange={setViewMode}
            ariaLabel="Analysis view mode"
            theme={theme}
            options={[
              { value: 'rendered', label: 'Rendered' },
              { value: 'raw', label: 'Raw' },
            ]}
          />
        </div>
      }
      headerRightActions={
        <>
          {/* Print button */}
          <Tooltip label="Print analysis">
          <Button variant="icon" theme={theme} onClick={handlePrint} aria-label="Print analysis">
            <Printer className="w-4 h-4" />
          </Button>
          </Tooltip>
          {/* Copy button */}
          <Tooltip label={copied ? 'Copied!' : 'Copy to clipboard'}>
          <Button
            variant="icon"
            theme={theme}
            onClick={handleCopy}
            aria-label={copied ? 'Copied!' : 'Copy to clipboard'}
            className={copied ? themeClasses.text(theme) : undefined}
          >
            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
          </Button>
          </Tooltip>
          {/* Delete button */}
          <Tooltip label="Delete analysis">
          <Button variant="icon" theme={theme} onClick={handleDelete} aria-label="Delete analysis">
            <Trash2 className="w-4 h-4" />
          </Button>
          </Tooltip>
        </>
      }
      footer={
        <div className={`text-xs flex items-center justify-between ${themeClasses.textSecondary(theme)}`}>
          <div>
            Generated by <span className={`font-medium ${themeClasses.text(theme)}`}>{currentAnalysis.createdBy}</span>
          </div>
          <div>
            {new Date(currentAnalysis.createdAt).toLocaleString()}
          </div>
        </div>
      }
    >
          {viewMode === 'rendered' ? (
            <div
              id="ai-analysis-rendered-content"
              className={`prose ${theme === 'dark' ? 'prose-invert' : ''} max-w-none
                prose-headings:font-bold
                prose-h1:text-lg prose-h1:mb-2 prose-h1:mt-0 prose-h1:pb-1.5 prose-h1:border-b ${theme === 'dark' ? 'prose-h1:border-[#333]' : 'prose-h1:border-gray-300'}
                prose-h2:text-base prose-h2:mt-4 prose-h2:mb-2 prose-h2:font-semibold
                prose-h3:text-sm prose-h3:mt-3 prose-h3:mb-1.5 prose-h3:font-semibold
                prose-h4:text-sm prose-h4:mt-2.5 prose-h4:mb-1 prose-h4:font-medium
                prose-p:leading-5 prose-p:my-2 prose-p:text-sm
                prose-strong:font-bold
                prose-li:my-0.5 prose-li:leading-5 prose-li:text-sm
                prose-ul:my-2 prose-ul:space-y-0.5 prose-ul:pl-5
                prose-ol:my-2 prose-ol:space-y-0.5 prose-ol:pl-5
                prose-a:text-accent prose-a:no-underline hover:prose-a:underline
                prose-code:text-pink-400 ${theme === 'dark' ? 'prose-code:bg-[#0a0a0a]' : 'prose-code:bg-gray-100'} prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:text-xs prose-code:font-mono
                ${theme === 'dark' ? 'prose-pre:bg-[#0a0a0a] prose-pre:border-[#2a2a2a]' : 'prose-pre:bg-gray-100 prose-pre:border-gray-300'} prose-pre:border prose-pre:rounded-lg prose-pre:p-3 prose-pre:my-2 prose-pre:text-xs
                ${theme === 'dark' ? 'prose-hr:border-[#333]' : 'prose-hr:border-gray-300'} prose-hr:my-4
                prose-blockquote:border-l-4 prose-blockquote:border-accent prose-blockquote:pl-3 prose-blockquote:italic prose-blockquote:my-2 prose-blockquote:text-sm
                prose-table:text-xs prose-table:my-2
                ${theme === 'dark' ? 'prose-th:bg-[#0a0a0a] prose-th:border-[#333] prose-td:border-[#333]' : 'prose-th:bg-gray-100 prose-th:border-gray-300 prose-td:border-gray-300'} prose-th:font-semibold prose-th:p-2 prose-td:p-2
              `}
            >
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {currentAnalysis.findings}
              </ReactMarkdown>
            </div>
          ) : (
            <div className={`prose ${theme === 'dark' ? 'prose-invert' : ''} prose-sm max-w-none`}>
              <div className={`whitespace-pre-wrap leading-tight font-mono text-xs ${themeClasses.text(theme)}`}>
                {currentAnalysis.findings}
              </div>
            </div>
          )}
    </Modal>
  )
}
