import { useState, useCallback } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { jsPDF } from 'jspdf'
import { FileText } from 'lucide-react'
import { Modal } from '@/components/ui/Modal'
import { useAiAnalysisStore } from '@/stores/aiAnalysisStore'
import { useStudyStore } from '@/stores/studyStore'
import { useErrorHandler } from '@/hooks/useErrorHandler'
import { isTauri } from '@/lib/utils/platform'

export function AiAnalysisModal() {
  const isModalVisible = useAiAnalysisStore((state) => state.isModalVisible)
  const selectedAnalysisId = useAiAnalysisStore((state) => state.selectedAnalysisId)
  const analyses = useAiAnalysisStore((state) => state.analyses)
  const hideModal = useAiAnalysisStore((state) => state.hideModal)
  const deleteAnalysis = useAiAnalysisStore((state) => state.deleteAnalysis)
  const currentInstance = useStudyStore((state) => state.currentInstance)

  const [viewMode, setViewMode] = useState<'rendered' | 'raw'>('rendered')
  const [copied, setCopied] = useState(false)

  const { handleError } = useErrorHandler()

  // Get the analysis for the current image
  const currentAnalysis = currentInstance
    ? analyses.find((a) => a.sopInstanceUID === currentInstance.sopInstanceUID)
    : null

  const handleDelete = () => {
    if (!currentAnalysis) return
    if (confirm('Are you sure you want to delete this AI analysis?')) {
      deleteAnalysis(currentAnalysis.id)
    }
  }


  const handleCopy = useCallback(async () => {
    if (!currentAnalysis) return
    try {
      await navigator.clipboard.writeText(currentAnalysis.findings)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy to clipboard:', err)
    }
  }, [currentAnalysis])

  const handlePrint = useCallback(async () => {
    if (!currentAnalysis) return

    console.log('Generating PDF...', { isTauri: isTauri() })

    try {
      // Create PDF document
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      })

      // PDF dimensions
      const pageWidth = pdf.internal.pageSize.getWidth()
      const pageHeight = pdf.internal.pageSize.getHeight()
      const margin = 20
      const maxWidth = pageWidth - (margin * 2)
      let yPos = margin

      // Helper to add text with word wrapping
      const addText = (text: string, fontSize: number, fontStyle: 'normal' | 'bold' = 'normal', leftMargin = 0) => {
        pdf.setFontSize(fontSize)
        pdf.setFont('helvetica', fontStyle)
        const lines = pdf.splitTextToSize(text, maxWidth - leftMargin)

        lines.forEach((line: string) => {
          // Check if we need a new page
          if (yPos > pageHeight - margin) {
            pdf.addPage()
            yPos = margin
          }
          pdf.text(line, margin + leftMargin, yPos)
          yPos += fontSize * 0.5
        })
        yPos += 3 // Extra spacing after paragraph
      }

      // Add title
      pdf.setFontSize(20)
      pdf.setFont('helvetica', 'bold')
      pdf.text('AI Radiology Analysis', margin, yPos)
      yPos += 12

      // Add metadata
      pdf.setFontSize(9)
      pdf.setFont('helvetica', 'normal')
      pdf.setTextColor(100, 100, 100)
      pdf.text(`Generated by ${currentAnalysis.createdBy} • ${new Date(currentAnalysis.createdAt).toLocaleString()}`, margin, yPos)
      yPos += 10
      pdf.setTextColor(0, 0, 0)

      // Add line separator
      pdf.setDrawColor(200, 200, 200)
      pdf.line(margin, yPos, pageWidth - margin, yPos)
      yPos += 8

      // Parse and add content based on view mode
      if (viewMode === 'raw') {
        // Raw markdown - just add as monospace text
        pdf.setFont('courier', 'normal')
        pdf.setFontSize(9)
        const lines = currentAnalysis.findings.split('\n')
        lines.forEach(line => {
          if (yPos > pageHeight - margin) {
            pdf.addPage()
            yPos = margin
          }
          pdf.text(line || ' ', margin, yPos)
          yPos += 4
        })
      } else {
        // Rendered view - parse markdown into formatted text
        const lines = currentAnalysis.findings.split('\n')

        for (const line of lines) {
          if (!line.trim()) {
            yPos += 3
            continue
          }

          // Headers
          if (line.startsWith('# ')) {
            yPos += 5
            addText(line.substring(2), 16, 'bold')
          } else if (line.startsWith('## ')) {
            yPos += 4
            addText(line.substring(3), 14, 'bold')
          } else if (line.startsWith('### ')) {
            yPos += 3
            addText(line.substring(4), 12, 'bold')
          } else if (line.startsWith('#### ')) {
            yPos += 2
            addText(line.substring(5), 11, 'bold')
          }
          // Bullet points
          else if (line.match(/^[\*\-\+]\s/)) {
            const text = '• ' + line.substring(2)
            addText(text, 10, 'normal', 5)
          }
          // Numbered lists
          else if (line.match(/^\d+\.\s/)) {
            addText(line, 10, 'normal', 5)
          }
          // Bold text (simple parsing)
          else if (line.includes('**')) {
            const text = line.replace(/\*\*(.*?)\*\*/g, '$1')
            addText(text, 10, 'bold')
          }
          // Regular paragraph
          else {
            addText(line, 10, 'normal')
          }
        }
      }

      // Generate PDF
      const pdfBlob = pdf.output('blob')
      const fileName = `AI_Analysis_${new Date().toISOString().slice(0, 10)}.pdf`

      if (isTauri()) {
        // In Tauri, save to Downloads directory
        const { writeFile } = await import('@tauri-apps/plugin-fs')
        const { save } = await import('@tauri-apps/plugin-dialog')

        // Convert blob to Uint8Array
        const arrayBuffer = await pdfBlob.arrayBuffer()
        const uint8Array = new Uint8Array(arrayBuffer)

        // Let user choose where to save the PDF
        const filePath = await save({
          defaultPath: fileName,
          filters: [{
            name: 'PDF',
            extensions: ['pdf']
          }]
        })

        if (filePath) {
          await writeFile(filePath, uint8Array)
          handleError(`PDF saved to: ${filePath}`, 'PDF Export', 'info')
        }
      } else {
        // In browser, open PDF in new tab
        const pdfUrl = URL.createObjectURL(pdfBlob)
        const newWindow = window.open(pdfUrl, '_blank')

        if (!newWindow) {
          // Fallback: download the PDF
          const link = document.createElement('a')
          link.href = pdfUrl
          link.download = fileName
          link.click()
          URL.revokeObjectURL(pdfUrl)
        } else {
          // Clean up URL after a delay
          setTimeout(() => URL.revokeObjectURL(pdfUrl), 1000)
        }
      }
    } catch (err) {
      handleError(err as Error, 'PDF Export', 'error')
    }
  }, [currentAnalysis, viewMode])

  // Don't render anything if modal is not visible
  // Analysis indicator is now shown only in the thumbnail strip
  if (!isModalVisible || !selectedAnalysisId || !currentAnalysis) return null

  return (
    <Modal
      show={isModalVisible}
      onClose={hideModal}
      title="AI Radiology Analysis"
      icon={<FileText />}
      headerLeftActions={
        /* View mode toggle */
        /* Button styling pattern: Active state uses gray background (bg-[#2a2a2a]) with white text, NOT blue.
           This matches the app toolbar styling in App.tsx header. Hover uses blue accent color for icons. */
        <div className="flex ml-3 bg-[#0a0a0a] rounded overflow-hidden border border-[#333]">
          <button
            onClick={() => setViewMode('rendered')}
            className={`px-2.5 py-1 text-xs font-medium transition-colors ${
              viewMode === 'rendered'
                ? 'bg-[#2a2a2a] text-white'
                : 'text-gray-400 hover:text-gray-200 hover:bg-[#1a1a1a]'
            }`}
          >
            Rendered
          </button>
          <button
            onClick={() => setViewMode('raw')}
            className={`px-2.5 py-1 text-xs font-medium transition-colors ${
              viewMode === 'raw'
                ? 'bg-[#2a2a2a] text-white'
                : 'text-gray-400 hover:text-gray-200 hover:bg-[#1a1a1a]'
            }`}
          >
            Raw
          </button>
        </div>
      }
      headerRightActions={
        <>
          {/* Print button */}
          <button
            onClick={handlePrint}
            title="Print analysis"
            className="p-1.5 text-gray-400 hover:text-white hover:bg-[#2a2a2a] rounded transition-colors"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
              fill="currentColor"
              className="w-4 h-4"
            >
              <path
                fillRule="evenodd"
                d="M5 2.75C5 1.784 5.784 1 6.75 1h6.5c.966 0 1.75.784 1.75 1.75v3.552c.377.046.752.097 1.126.153A2.212 2.212 0 0118 8.653v4.097A2.25 2.25 0 0115.75 15h-.55a.75.75 0 000-1.5h.55a.75.75 0 00.75-.75V8.653a.712.712 0 00-.615-.711 47.965 47.965 0 00-11.77 0 .712.712 0 00-.615.711v4.097c0 .414.336.75.75.75h.55a.75.75 0 000 1.5h-.55A2.25 2.25 0 012 12.75V8.653c0-1.082.775-2.034 1.874-2.198.374-.056.749-.107 1.126-.153V2.75zm1.5 0v3.36a49.323 49.323 0 017 0V2.75a.25.25 0 00-.25-.25h-6.5a.25.25 0 00-.25.25zM14 13a.75.75 0 00-.75-.75h-6.5a.75.75 0 00-.75.75v4.25c0 .414.336.75.75.75h6.5a.75.75 0 00.75-.75V13zm-1.5.75v2.75h-5v-2.75h5z"
                clipRule="evenodd"
              />
            </svg>
          </button>
          {/* Copy button */}
          <button
            onClick={handleCopy}
            title={copied ? 'Copied!' : 'Copy to clipboard'}
            className={`p-1.5 hover:bg-[#2a2a2a] rounded transition-colors ${
              copied ? 'text-white' : 'text-gray-400 hover:text-white'
            }`}
          >
            {copied ? (
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
                className="w-4 h-4"
              >
                <path
                  fillRule="evenodd"
                  d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z"
                  clipRule="evenodd"
                />
              </svg>
            ) : (
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
                className="w-4 h-4"
              >
                <path d="M7 3.5A1.5 1.5 0 018.5 2h3.879a1.5 1.5 0 011.06.44l3.122 3.12A1.5 1.5 0 0117 6.622V12.5a1.5 1.5 0 01-1.5 1.5h-1v-3.379a3 3 0 00-.879-2.121L10.5 5.379A3 3 0 008.379 4.5H7v-1z" />
                <path d="M4.5 6A1.5 1.5 0 003 7.5v9A1.5 1.5 0 004.5 18h7a1.5 1.5 0 001.5-1.5v-5.879a1.5 1.5 0 00-.44-1.06L9.44 6.439A1.5 1.5 0 008.378 6H4.5z" />
              </svg>
            )}
          </button>
          {/* Delete button */}
          <button
            onClick={handleDelete}
            title="Delete analysis"
            className="p-1.5 text-gray-400 hover:text-white hover:bg-[#2a2a2a] rounded transition-colors"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
              fill="currentColor"
              className="w-4 h-4"
            >
              <path
                fillRule="evenodd"
                d="M8.75 1A2.75 2.75 0 006 3.75v.443c-.795.077-1.584.176-2.365.298a.75.75 0 10.23 1.482l.149-.022.841 10.518A2.75 2.75 0 007.596 19h4.807a2.75 2.75 0 002.742-2.53l.841-10.52.149.023a.75.75 0 00.23-1.482A41.03 41.03 0 0014 4.193V3.75A2.75 2.75 0 0011.25 1h-2.5zM10 4c.84 0 1.673.025 2.5.075V3.75c0-.69-.56-1.25-1.25-1.25h-2.5c-.69 0-1.25.56-1.25 1.25v.325C8.327 4.025 9.16 4 10 4zM8.58 7.72a.75.75 0 00-1.5.06l.3 7.5a.75.75 0 101.5-.06l-.3-7.5zm4.34.06a.75.75 0 10-1.5-.06l-.3 7.5a.75.75 0 101.5.06l.3-7.5z"
                clipRule="evenodd"
              />
            </svg>
          </button>
        </>
      }
      footer={
        <div className="text-xs text-gray-500 flex items-center justify-between">
          <div>
            Generated by <span className="text-gray-400 font-medium">{currentAnalysis.createdBy}</span>
          </div>
          <div>
            {new Date(currentAnalysis.createdAt).toLocaleString()}
          </div>
        </div>
      }
    >
          {viewMode === 'rendered' ? (
            <div
              id="ai-analysis-rendered-content"
              className="prose prose-invert max-w-none
                prose-headings:text-white prose-headings:font-bold
                prose-h1:text-lg prose-h1:mb-2 prose-h1:mt-0 prose-h1:pb-1.5 prose-h1:border-b prose-h1:border-[#333]
                prose-h2:text-base prose-h2:mt-4 prose-h2:mb-2 prose-h2:font-semibold
                prose-h3:text-sm prose-h3:mt-3 prose-h3:mb-1.5 prose-h3:font-semibold
                prose-h4:text-sm prose-h4:mt-2.5 prose-h4:mb-1 prose-h4:font-medium
                prose-p:text-gray-200 prose-p:leading-5 prose-p:my-2 prose-p:text-sm
                prose-strong:text-white prose-strong:font-bold
                prose-li:text-gray-200 prose-li:my-0.5 prose-li:leading-5 prose-li:text-sm
                prose-ul:my-2 prose-ul:space-y-0.5 prose-ul:pl-5
                prose-ol:my-2 prose-ol:space-y-0.5 prose-ol:pl-5
                prose-a:text-blue-400 prose-a:no-underline hover:prose-a:underline
                prose-code:text-pink-400 prose-code:bg-[#0a0a0a] prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:text-xs prose-code:font-mono
                prose-pre:bg-[#0a0a0a] prose-pre:border prose-pre:border-[#2a2a2a] prose-pre:rounded-lg prose-pre:p-3 prose-pre:my-2 prose-pre:text-xs
                prose-hr:border-[#333] prose-hr:my-4
                prose-blockquote:border-l-4 prose-blockquote:border-blue-500 prose-blockquote:pl-3 prose-blockquote:text-gray-300 prose-blockquote:italic prose-blockquote:my-2 prose-blockquote:text-sm
                prose-table:text-xs prose-table:my-2
                prose-th:text-white prose-th:bg-[#0a0a0a] prose-th:font-semibold prose-th:p-2
                prose-td:text-gray-200 prose-td:border-[#333] prose-td:p-2
                prose-th:border-[#333]
              "
            >
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {currentAnalysis.findings}
              </ReactMarkdown>
            </div>
          ) : (
            <div className="prose prose-invert prose-sm max-w-none">
              <div className="whitespace-pre-wrap text-gray-300 leading-tight font-mono text-xs">
                {currentAnalysis.findings}
              </div>
            </div>
          )}
    </Modal>
  )
}
