import { useEffect, useState, useMemo } from 'react'
import { useAnnotationStore } from '@/stores/annotationStore'
import { useViewportStore } from '@/stores/viewportStore'
import { useStudyStore } from '@/stores/studyStore'
import { MarkerAnnotation, MeasurementAnnotation, RegionAnnotation, Point2D } from '@/types/annotation'
import { annotationColors } from '@/lib/colors'
// @ts-expect-error - cornerstone-core doesn't have TypeScript definitions
import cornerstone from 'cornerstone-core'

interface AnnotationOverlayProps {
  canvasElement: HTMLDivElement | null
}

export function AnnotationOverlay({ canvasElement }: AnnotationOverlayProps) {
  const [dimensions, setDimensions] = useState({ width: 0, height: 0 })
  const showAnnotations = useViewportStore((state) => state.showAnnotations)
  const currentInstance = useStudyStore((state) => state.currentInstance)
  const allAnnotations = useAnnotationStore((state) => state.annotations)
  const areMarkersVisible = useAnnotationStore((state) =>
    currentInstance ? state.areMarkersVisible(currentInstance.sopInstanceUID) : true
  )

  // Track canvas dimensions
  useEffect(() => {
    if (!canvasElement) return

    const updateDimensions = () => {
      const rect = canvasElement.getBoundingClientRect()
      setDimensions({ width: rect.width, height: rect.height })
    }

    // Initial dimensions
    updateDimensions()

    // Watch for resize
    const resizeObserver = new ResizeObserver(updateDimensions)
    resizeObserver.observe(canvasElement)

    return () => {
      resizeObserver.disconnect()
    }
  }, [canvasElement])

  // Get annotations for current instance (only if markers are visible).
  // Dedupe by id so a duplicated annotation (e.g. from persisted state) can
  // never produce duplicate React keys / duplicated-or-omitted SVG children.
  const annotations = useMemo(() => {
    if (!currentInstance || !showAnnotations || !areMarkersVisible) return []
    const seen = new Set<string>()
    return allAnnotations.filter((ann) => {
      if (ann.sopInstanceUID !== currentInstance.sopInstanceUID) return false
      if (seen.has(ann.id)) return false
      seen.add(ann.id)
      return true
    })
  }, [currentInstance, showAnnotations, areMarkersVisible, allAnnotations])


  if (!canvasElement || !currentInstance || !showAnnotations || annotations.length === 0) {
    return null
  }

  // Wait for dimensions to be set by ResizeObserver
  if (dimensions.width === 0 || dimensions.height === 0) {
    return null
  }

  return (
    <svg
      className="absolute inset-0"
      width={dimensions.width}
      height={dimensions.height}
      style={{ zIndex: 10, pointerEvents: 'none' }}
    >
      {annotations.map((annotation) => {
        if (annotation.type === 'marker') {
          return (
            <MarkerRenderer
              key={annotation.id}
              annotation={annotation}
              canvasElement={canvasElement}
            />
          )
        }
        if (annotation.type === 'measurement') {
          return (
            <MeasurementRenderer
              key={annotation.id}
              annotation={annotation}
              canvasElement={canvasElement}
            />
          )
        }
        if (annotation.type === 'region') {
          return (
            <RegionRenderer
              key={annotation.id}
              annotation={annotation}
              canvasElement={canvasElement}
            />
          )
        }
        return null
      })}
    </svg>
  )
}

interface MarkerRendererProps {
  annotation: MarkerAnnotation
  canvasElement: HTMLDivElement
}

function MarkerRenderer({ annotation, canvasElement }: MarkerRendererProps) {
  const [isDragging, setIsDragging] = useState(false)
  const [dragOffset, setDragOffset] = useState({ x: 0, y: 0 })
  const [showContextMenu, setShowContextMenu] = useState(false)
  const [contextMenuPos, setContextMenuPos] = useState({ x: 0, y: 0 })
  const updateAnnotation = useAnnotationStore((state) => state.updateAnnotation)
  const deleteAnnotationsForInstance = useAnnotationStore((state) => state.deleteAnnotationsForInstance)
  const currentInstance = useStudyStore((state) => state.currentInstance)
  const allAnnotations = useAnnotationStore((state) => state.annotations)

  // Check if there are any AI markers in the current instance
  const hasAiMarkers = currentInstance
    ? allAnnotations.some(a =>
        a.sopInstanceUID === currentInstance.sopInstanceUID &&
        a.type === 'marker' &&
        a.autoGenerated
      )
    : false

  // Close context menu when clicking elsewhere
  useEffect(() => {
    if (!showContextMenu) return

    const handleClick = () => setShowContextMenu(false)
    document.addEventListener('click', handleClick)
    return () => document.removeEventListener('click', handleClick)
  }, [showContextMenu])

  // Check if an image is loaded before trying to convert coordinates
  let hasImage = false
  try {
    const image = cornerstone.getImage(canvasElement)
    hasImage = !!image
  } catch (err) {
    hasImage = false
  }

  if (!hasImage) {
    return null // No image loaded yet
  }

  // Convert image pixel coordinates to canvas coordinates using Cornerstone
  // This properly handles viewport transformations (scale, translation, rotation)
  const imageCoords = { x: annotation.position.x, y: annotation.position.y }
  const canvasCoords = cornerstone.pixelToCanvas(canvasElement, imageCoords)

  const viewportX = canvasCoords.x + dragOffset.x
  const viewportY = canvasCoords.y + dragOffset.y

  const radius = 8
  const labelOffsetX = 12
  const labelOffsetY = 5

  // Use orange for all markers
  const markerColor = annotationColors.orange
  // Fill opacity: solid when manually adjusted, transparent when automatic
  const fillOpacity = annotation.manuallyAdjusted ? 0.8 : 0.15
  const strokeWidth = 1.5

  const handleMouseDown = (e: React.MouseEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setIsDragging(true)
  }

  const handleMouseMove = (e: React.MouseEvent) => {
    if (!isDragging) return

    setDragOffset({
      x: dragOffset.x + e.movementX,
      y: dragOffset.y + e.movementY
    })
  }

  const handleMouseUp = () => {
    if (!isDragging) return

    // Convert final canvas position back to image coordinates
    const finalCanvasX = canvasCoords.x + dragOffset.x
    const finalCanvasY = canvasCoords.y + dragOffset.y
    const finalImageCoords = cornerstone.canvasToPixel(canvasElement, { x: finalCanvasX, y: finalCanvasY })

    const deltaX = finalImageCoords.x - annotation.position.x
    const deltaY = finalImageCoords.y - annotation.position.y

    // Only update if there was actual movement (> 0.5px threshold to avoid floating point errors)
    if (Math.abs(deltaX) > 0.5 || Math.abs(deltaY) > 0.5) {
      console.log(`[AnnotationOverlay] ${annotation.label} adjusted: (${deltaX.toFixed(1)}, ${deltaY.toFixed(1)})px`)

      // Update the annotation with corrected position
      updateAnnotation(annotation.id, {
        position: {
          x: finalImageCoords.x,
          y: finalImageCoords.y
        }
      })
    }

    setIsDragging(false)
    setDragOffset({ x: 0, y: 0 })
  }

  const handleContextMenu = (e: React.MouseEvent) => {
    // Only show context menu if there are AI markers
    if (!hasAiMarkers) return

    e.preventDefault()
    e.stopPropagation()

    // Get SVG element to calculate proper coordinates
    const svgElement = (e.target as SVGElement).ownerSVGElement
    if (!svgElement) return

    const rect = svgElement.getBoundingClientRect()
    setContextMenuPos({
      x: e.clientX - rect.left,
      y: e.clientY - rect.top
    })
    setShowContextMenu(true)
  }

  const handleDeleteAllAiMarkers = () => {
    if (!currentInstance) return
    deleteAnnotationsForInstance(currentInstance.sopInstanceUID, true) // Only delete AI-generated
    setShowContextMenu(false)
  }

  return (
    <>
    <g
      onMouseDown={handleMouseDown}
      onMouseMove={handleMouseMove}
      onMouseUp={handleMouseUp}
      onMouseLeave={handleMouseUp}
      onContextMenu={handleContextMenu}
      style={{ cursor: isDragging ? 'grabbing' : 'grab', pointerEvents: 'all' }}
    >
      {/* Marker circle */}
      <circle
        cx={viewportX}
        cy={viewportY}
        r={radius}
        fill={markerColor}
        fillOpacity={fillOpacity}
        stroke={markerColor}
        strokeWidth={strokeWidth}
      />

      {/* Label */}
      {annotation.label && (
        <text
          x={viewportX + labelOffsetX}
          y={viewportY + labelOffsetY}
          fill={markerColor}
          fontSize="12px"
          fontWeight="bold"
          fontFamily="sans-serif"
          style={{ pointerEvents: 'none', userSelect: 'none' }}
        >
          {annotation.label}
        </text>
      )}
    </g>

    {/* Context menu */}
    {showContextMenu && hasAiMarkers && (
      <foreignObject
        x={contextMenuPos.x}
        y={contextMenuPos.y}
        width="180"
        height="40"
        style={{ overflow: 'visible' }}
      >
        <div
          className="bg-[#1a1a1a] border border-[#3a3a3a] rounded shadow-lg py-1"
          style={{ pointerEvents: 'all' }}
        >
          <button
            onClick={handleDeleteAllAiMarkers}
            className="w-full px-3 py-1.5 text-left text-sm text-red-400 hover:bg-[#2a2a2a] transition-colors flex items-center gap-2"
          >
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4">
              <path fillRule="evenodd" d="M8.75 1A2.75 2.75 0 006 3.75v.443c-.795.077-1.584.176-2.365.298a.75.75 0 10.23 1.482l.149-.022.841 10.518A2.75 2.75 0 007.596 19h4.807a2.75 2.75 0 002.742-2.53l.841-10.52.149.023a.75.75 0 00.23-1.482A41.03 41.03 0 0014 4.193V3.75A2.75 2.75 0 0011.25 1h-2.5zM10 4c.84 0 1.673.025 2.5.075V3.75c0-.69-.56-1.25-1.25-1.25h-2.5c-.69 0-1.25.56-1.25 1.25v.325C8.327 4.025 9.16 4 10 4zM8.58 7.72a.75.75 0 00-1.5.06l.3 7.5a.75.75 0 101.5-.06l-.3-7.5zm4.34.06a.75.75 0 10-1.5-.06l-.3 7.5a.75.75 0 101.5.06l.3-7.5z" clipRule="evenodd" />
            </svg>
            Delete AI markers
          </button>
        </div>
      </foreignObject>
    )}
    </>
  )
}

/** Convert an image-pixel point to canvas coordinates, or null if no image. */
function pixelToCanvasSafe(canvasElement: HTMLDivElement, point: Point2D): Point2D | null {
  try {
    const image = cornerstone.getImage(canvasElement)
    if (!image) return null
    return cornerstone.pixelToCanvas(canvasElement, { x: point.x, y: point.y })
  } catch {
    return null
  }
}

const MEASUREMENT_COLOR = annotationColors.cyan

interface MeasurementRendererProps {
  annotation: MeasurementAnnotation
  canvasElement: HTMLDivElement
}

/**
 * Renders a persisted length / angle measurement as a static SVG overlay so it
 * remains visible after a reload (cornerstone-tools owns the interactive copy
 * within a session). Read-only — purely a visual record of the stored value.
 */
function MeasurementRenderer({ annotation, canvasElement }: MeasurementRendererProps) {
  const canvasPoints = annotation.points
    .map((p) => pixelToCanvasSafe(canvasElement, p))
    .filter((p): p is Point2D => p !== null)

  if (canvasPoints.length !== annotation.points.length || canvasPoints.length < 2) {
    return null
  }

  // Polyline through all points (2 for length, 3 for angle).
  const pointsAttr = canvasPoints.map((p) => `${p.x},${p.y}`).join(' ')
  // Label near the last point (vertex for angle, endpoint for length).
  const labelPoint = canvasPoints[canvasPoints.length - 1]

  return (
    <g style={{ pointerEvents: 'none' }}>
      <polyline
        points={pointsAttr}
        fill="none"
        stroke={MEASUREMENT_COLOR}
        strokeWidth={1.5}
      />
      {canvasPoints.map((p, i) => (
        <circle key={i} cx={p.x} cy={p.y} r={3} fill={MEASUREMENT_COLOR} />
      ))}
      <text
        x={labelPoint.x + 8}
        y={labelPoint.y - 8}
        fill={MEASUREMENT_COLOR}
        fontSize="12px"
        fontWeight="bold"
        fontFamily="sans-serif"
        style={{ userSelect: 'none' }}
      >
        {annotation.value.toFixed(1)} {annotation.unit}
      </text>
    </g>
  )
}

interface RegionRendererProps {
  annotation: RegionAnnotation
  canvasElement: HTMLDivElement
}

/**
 * Renders a persisted rectangular/elliptical ROI bounding box as a static SVG
 * overlay (stored as top-left / bottom-right corner points). Read-only record.
 */
function RegionRenderer({ annotation, canvasElement }: RegionRendererProps) {
  if (annotation.points.length < 2) return null

  const start = pixelToCanvasSafe(canvasElement, annotation.points[0])
  const end = pixelToCanvasSafe(canvasElement, annotation.points[1])
  if (!start || !end) return null

  const x = Math.min(start.x, end.x)
  const y = Math.min(start.y, end.y)
  const width = Math.abs(end.x - start.x)
  const height = Math.abs(end.y - start.y)

  return (
    <g style={{ pointerEvents: 'none' }}>
      <rect
        x={x}
        y={y}
        width={width}
        height={height}
        fill={MEASUREMENT_COLOR}
        fillOpacity={0.08}
        stroke={MEASUREMENT_COLOR}
        strokeWidth={1.5}
      />
      <text
        x={x + 4}
        y={y - 6}
        fill={MEASUREMENT_COLOR}
        fontSize="11px"
        fontWeight="bold"
        fontFamily="sans-serif"
        style={{ userSelect: 'none' }}
      >
        {annotation.description}
      </text>
    </g>
  )
}
