import { DicomInstance } from '@/types'
import { MarkerAnnotation } from '@/types/annotation'
import { DetectionResult } from './types'

export type { DetectionResult }

/**
 * Mock vertebrae detector for MVP development.
 * Simulates AI detection with realistic delay and anatomically-plausible positioning.
 * Easy to replace with real TensorFlow.js model later.
 */
export class MockVertebralDetector {
  /**
   * Detects vertebrae in a DICOM image (simulated).
   * Generates L1-L5 markers positioned in center column with anatomical spacing.
   */
  async detectVertebrae(instance: DicomInstance): Promise<DetectionResult> {
    const startTime = performance.now()

    // Simulate realistic AI processing delay
    const delay = 500 + Math.random() * 1000 // 500-1500ms
    await new Promise(resolve => setTimeout(resolve, delay))

    // Generate anatomically-plausible marker positions
    const annotations: MarkerAnnotation[] = []
    const vertebrae = ['L1', 'L2', 'L3', 'L4', 'L5']

    // Position vertebrae in center column, starting from top
    const centerX = instance.columns / 2
    const startY = instance.rows * 0.2  // Start 20% from top
    const spacing = instance.rows * 0.12  // 12% spacing between vertebrae

    vertebrae.forEach((label, index) => {
      // Add small random offset for realism
      const offsetX = (Math.random() - 0.5) * 10
      const offsetY = (Math.random() - 0.5) * 5

      const annotation: MarkerAnnotation = {
        id: `ai-${instance.sopInstanceUID}-${label}-${Date.now()}-${index}`,
        type: 'marker',
        seriesInstanceUID: instance.metadata?.seriesDescription || '',
        sopInstanceUID: instance.sopInstanceUID,
        instanceNumber: instance.instanceNumber,
        severity: 'normal',
        description: `AI-detected ${label} vertebra`,
        createdAt: new Date().toISOString(),
        createdBy: 'AI-Detector',
        autoGenerated: true,
        modelVersion: 'mock-v1.0',
        position: {
          x: centerX + offsetX,
          y: startY + (index * spacing) + offsetY,
        },
        label,
      }

      annotations.push(annotation)
    })

    const processingTimeMs = performance.now() - startTime

    return {
      annotations,
      confidence: 0.85 + Math.random() * 0.1, // 85-95% confidence
      processingTimeMs,
    }
  }
}

// Export singleton instance
export const mockDetector = new MockVertebralDetector()
