/**
 * MR segmentation contract + conversion to OpenScans annotations.
 *
 * Unlike the cloud/local vision detectors (which analyze a single rendered 2D
 * PNG), the MR-precision engine (TotalSegmentator-MRI / MONAI) runs on the
 * whole DICOM **series** and produces a 3D label map. The Python engine
 * resolves each structure's centroid back to a specific DICOM instance +
 * pixel coordinate, so the frontend only has to map those landmarks onto
 * marker annotations. See `python-engine/mr_segmentation/` and
 * `src-tauri/src/mr_seg.rs`.
 */
import { MarkerAnnotation } from '@/types/annotation'

/** One resolved landmark from the segmentation engine. */
export interface MrStructure {
  /** Anatomical label, e.g. 'L1', 'T12', 'vertebrae_L3'. */
  label: string
  /** DICOM instance the centroid lands on. */
  sopInstanceUID: string
  /** Instance number of that slice within the series. */
  instanceNumber: number
  /** Centroid pixel coordinate within that instance (top-left origin). */
  position: { x: number; y: number }
  /** Confidence in 0..1. */
  confidence: number
}

/** Engine output (one run over a whole series). */
export interface MrSegmentationResult {
  /** Engine identifier, e.g. 'totalsegmentator-mri'. */
  engine: string
  /** Engine/model version string. */
  version: string
  structures: MrStructure[]
}

export interface MarkerContext {
  seriesInstanceUID: string
  /** Model version string recorded on each annotation. */
  modelVersion: string
}

/** Narrowing guard for a single structure entry from untrusted engine output. */
export function isValidStructure(value: unknown): value is MrStructure {
  if (typeof value !== 'object' || value === null) return false
  const s = value as Record<string, unknown>
  const pos = s.position as Record<string, unknown> | undefined
  return (
    typeof s.label === 'string' &&
    s.label.length > 0 &&
    typeof s.sopInstanceUID === 'string' &&
    s.sopInstanceUID.length > 0 &&
    typeof s.instanceNumber === 'number' &&
    Number.isFinite(s.instanceNumber) &&
    typeof pos === 'object' &&
    pos !== null &&
    typeof pos.x === 'number' &&
    Number.isFinite(pos.x) &&
    typeof pos.y === 'number' &&
    Number.isFinite(pos.y) &&
    typeof s.confidence === 'number' &&
    Number.isFinite(s.confidence)
  )
}

/**
 * Validate raw engine JSON into an {@link MrSegmentationResult}, dropping any
 * malformed structure entries rather than throwing on a single bad landmark.
 */
export function parseSegmentationResult(raw: unknown): MrSegmentationResult {
  if (typeof raw !== 'object' || raw === null) {
    throw new Error('MR segmentation result is not an object')
  }
  const obj = raw as Record<string, unknown>
  const structuresRaw = Array.isArray(obj.structures) ? obj.structures : []
  const structures = structuresRaw.filter(isValidStructure)
  return {
    engine: typeof obj.engine === 'string' ? obj.engine : 'unknown',
    version: typeof obj.version === 'string' ? obj.version : 'unknown',
    structures,
  }
}

/**
 * Convert engine landmarks into marker annotations spanning the whole series.
 * Each marker is tagged with its own slice (`sopInstanceUID`/`instanceNumber`),
 * so the viewer renders them on the correct slices.
 */
export function segmentationToMarkers(
  result: MrSegmentationResult,
  ctx: MarkerContext
): MarkerAnnotation[] {
  const createdAt = new Date().toISOString()
  return result.structures.map((s, index) => ({
    id: `mr-seg-${s.sopInstanceUID}-${s.label}-${index}`,
    type: 'marker',
    seriesInstanceUID: ctx.seriesInstanceUID,
    sopInstanceUID: s.sopInstanceUID,
    instanceNumber: s.instanceNumber,
    severity: 'normal',
    description: `MR-segmented ${s.label} (confidence: ${(s.confidence * 100).toFixed(1)}%)`,
    createdAt,
    createdBy: ctx.modelVersion,
    autoGenerated: true,
    modelVersion: ctx.modelVersion,
    position: { x: s.position.x, y: s.position.y },
    label: s.label,
  }))
}
