/**
 * Unit tests for the MR segmentation contract parser + annotation converter.
 */
import { describe, it, expect } from 'vitest'
import {
  isValidStructure,
  parseSegmentationResult,
  segmentationToMarkers,
  type MrSegmentationResult,
} from './mrSegmentation'

const goodStructure = {
  label: 'L1',
  sopInstanceUID: 'sop-1',
  instanceNumber: 12,
  position: { x: 120, y: 240 },
  confidence: 0.91,
}

describe('isValidStructure', () => {
  it('accepts a well-formed structure', () => {
    expect(isValidStructure(goodStructure)).toBe(true)
  })

  it.each([
    ['missing label', { ...goodStructure, label: '' }],
    ['non-numeric position', { ...goodStructure, position: { x: 'a', y: 1 } }],
    ['NaN coordinate', { ...goodStructure, position: { x: NaN, y: 1 } }],
    ['missing sopInstanceUID', { ...goodStructure, sopInstanceUID: '' }],
    ['non-number confidence', { ...goodStructure, confidence: 'high' }],
    ['null', null],
  ])('rejects %s', (_label, value) => {
    expect(isValidStructure(value)).toBe(false)
  })
})

describe('parseSegmentationResult', () => {
  it('throws on a non-object', () => {
    expect(() => parseSegmentationResult('nope')).toThrow()
  })

  it('drops malformed structures but keeps valid ones', () => {
    const parsed = parseSegmentationResult({
      engine: 'totalsegmentator-mri',
      version: '2.0',
      structures: [goodStructure, { label: 'bad' }, { ...goodStructure, label: 'L2' }],
    })
    expect(parsed.engine).toBe('totalsegmentator-mri')
    expect(parsed.version).toBe('2.0')
    expect(parsed.structures.map((s) => s.label)).toEqual(['L1', 'L2'])
  })

  it('defaults engine/version and tolerates a missing structures array', () => {
    const parsed = parseSegmentationResult({})
    expect(parsed.engine).toBe('unknown')
    expect(parsed.version).toBe('unknown')
    expect(parsed.structures).toEqual([])
  })
})

describe('segmentationToMarkers', () => {
  const result: MrSegmentationResult = {
    engine: 'totalsegmentator-mri',
    version: '2.0',
    structures: [
      goodStructure,
      { label: 'L2', sopInstanceUID: 'sop-2', instanceNumber: 13, position: { x: 130, y: 250 }, confidence: 0.8 },
    ],
  }

  it('maps each structure to a marker on its own slice', () => {
    const markers = segmentationToMarkers(result, {
      seriesInstanceUID: 'series-1',
      modelVersion: 'totalsegmentator-mri@2.0',
    })

    expect(markers).toHaveLength(2)
    expect(markers[0]).toMatchObject({
      type: 'marker',
      seriesInstanceUID: 'series-1',
      sopInstanceUID: 'sop-1',
      instanceNumber: 12,
      position: { x: 120, y: 240 },
      label: 'L1',
      autoGenerated: true,
      modelVersion: 'totalsegmentator-mri@2.0',
    })
    // Second marker lands on a different slice — key property for MR series.
    expect(markers[1].sopInstanceUID).toBe('sop-2')
    expect(markers[1].instanceNumber).toBe(13)
  })

  it('produces unique annotation ids', () => {
    const markers = segmentationToMarkers(result, { seriesInstanceUID: 's', modelVersion: 'm' })
    const ids = new Set(markers.map((m) => m.id))
    expect(ids.size).toBe(markers.length)
  })
})
