/**
 * Unit tests for the MR segmentation bridge (ensureMrEngine, segmentSeries).
 * Tauri command/event APIs and the platform check are mocked.
 */
import { describe, it, expect, vi, beforeEach } from 'vitest'

const { invokeMock, listenMock } = vi.hoisted(() => ({
  invokeMock: vi.fn(),
  listenMock: vi.fn(),
}))

vi.mock('@tauri-apps/api/core', () => ({ invoke: invokeMock }))
vi.mock('@tauri-apps/api/event', () => ({ listen: listenMock }))

let underTauri = true
vi.mock('@/lib/utils/platform', () => ({ isTauri: () => underTauri }))

import { ensureMrEngine, segmentSeries } from './segmentationServer'

beforeEach(() => {
  vi.clearAllMocks()
  underTauri = true
  listenMock.mockResolvedValue(() => {})
})

describe('ensureMrEngine', () => {
  it('refuses to run outside the desktop app', async () => {
    underTauri = false
    await expect(ensureMrEngine()).rejects.toThrow(/desktop app/i)
    expect(invokeMock).not.toHaveBeenCalled()
  })

  it('downloads the engine when the binary is missing', async () => {
    invokeMock.mockImplementation((cmd: string) => {
      if (cmd === 'mr_seg_status') return Promise.resolve({ engineReady: false, modelReady: false })
      return Promise.resolve()
    })
    await ensureMrEngine()
    expect(invokeMock).toHaveBeenCalledWith('mr_seg_download')
  })

  it('does not re-download when the engine is already present', async () => {
    invokeMock.mockImplementation((cmd: string) => {
      if (cmd === 'mr_seg_status') return Promise.resolve({ engineReady: true, modelReady: false })
      return Promise.resolve()
    })
    await ensureMrEngine()
    expect(invokeMock).not.toHaveBeenCalledWith('mr_seg_download')
  })
})

describe('segmentSeries', () => {
  it('ensures the engine, runs it, and converts landmarks to markers', async () => {
    invokeMock.mockImplementation((cmd: string) => {
      if (cmd === 'mr_seg_status') return Promise.resolve({ engineReady: true, modelReady: true })
      if (cmd === 'mr_seg_run') {
        return Promise.resolve({
          engine: 'totalsegmentator-mri',
          version: '2.0',
          structures: [
            { label: 'L1', sopInstanceUID: 'sop-1', instanceNumber: 12, position: { x: 120, y: 240 }, confidence: 0.95 },
            { label: 'bad' }, // dropped by the validator
          ],
        })
      }
      return Promise.resolve()
    })

    const markers = await segmentSeries('/series', {
      seriesInstanceUID: 'series-1',
      modelVersion: 'totalsegmentator-mri@2.0',
    })

    expect(invokeMock).toHaveBeenCalledWith('mr_seg_run', { seriesDir: '/series' })
    expect(markers).toHaveLength(1)
    expect(markers[0]).toMatchObject({
      type: 'marker',
      label: 'L1',
      sopInstanceUID: 'sop-1',
      seriesInstanceUID: 'series-1',
      position: { x: 120, y: 240 },
      autoGenerated: true,
    })
  })
})
