/**
 * Integration tests for AI workflow
 *
 * Tests the complete AI detection and analysis workflow including
 * store interactions, annotation management, and error handling.
 */

import { describe, it, expect, beforeEach, vi } from 'vitest'
import { renderHook, act } from '@testing-library/react'
import { useAiOperations } from '@/hooks/useAiOperations'
import { useAnnotationStore } from '@/stores/annotationStore'
import { useAiAnalysisStore, type AiAnalysis } from '@/stores/aiAnalysisStore'
import { useStudyStore } from '@/stores/studyStore'
import { useErrorHandler } from '@/hooks/useErrorHandler'
import { createMockStudy, createMockInstance } from '@/test/fixtures/dicomData'
import type { MarkerAnnotation } from '@/types/annotation'

// Mock the AI detector
vi.mock('@/lib/ai/mockVertebralDetector', () => ({
  mockDetector: {
    detectVertebrae: vi.fn(),
    analyzeImage: vi.fn(),
    isConfigured: vi.fn(() => true),
    setApiKey: vi.fn(),
  },
}))

// Mock Claude detector
vi.mock('@/lib/ai/claudeVisionDetector', () => ({
  claudeDetector: {
    detectVertebrae: vi.fn(),
    analyzeImage: vi.fn(),
    isConfigured: vi.fn(() => true),
    setApiKey: vi.fn(),
  },
}))

// Mock settings store
vi.mock('@/stores/settingsStore', () => ({
  useSettingsStore: {
    getState: () => ({
      aiEnabled: true,
      aiProvider: 'claude',
      aiApiKey: 'test-key',
    }),
  },
}))

// Mock the AI detector manager
vi.mock('@/lib/ai/aiDetectorManager', () => ({
  initDetector: vi.fn(async (provider: string) => {
    if (provider === 'claude') {
      const { claudeDetector } = await import('@/lib/ai/claudeVisionDetector')
      return claudeDetector
    }
    const { mockDetector } = await import('@/lib/ai/mockVertebralDetector')
    return mockDetector
  }),
  getApiKeyForProvider: vi.fn((provider: string, keys: any) => {
    return keys.aiApiKey || keys.geminiApiKey || keys.openaiApiKey || ''
  }),
}))

describe('AI Workflow Integration', () => {
  let mockStudy: ReturnType<typeof createMockStudy>
  let mockInstance: ReturnType<typeof createMockInstance>

  beforeEach(() => {
    localStorage.clear() // Clear view state persistence
    useAnnotationStore.getState().reset()
    useAiAnalysisStore.getState().reset()
    useStudyStore.getState().reset()
    vi.clearAllMocks()

    mockStudy = createMockStudy(1, 3)
    mockInstance = mockStudy.series[0].instances[0]

    // Setup study store
    useStudyStore.getState().setStudies([mockStudy])
    useStudyStore.getState().setCurrentStudy(mockStudy.studyInstanceUID)
  })

  describe('AI vertebra detection workflow', () => {
    it('should run detection, clear old AI annotations, and add new ones', async () => {
      const { claudeDetector } = await import('@/lib/ai/claudeVisionDetector')

      const mockAnnotations: MarkerAnnotation[] = [
        {
          id: 'ai-ann-1',
          type: 'marker',
          sopInstanceUID: mockInstance.sopInstanceUID,
          seriesInstanceUID: mockInstance.metadata?.seriesDescription || '',
          instanceNumber: mockInstance.instanceNumber,
          position: { x: 256, y: 100 },
          label: 'L1',
          severity: 'normal',
          description: 'AI-detected marker',
          createdAt: new Date().toISOString(),
          createdBy: 'AI-Detector',
          autoGenerated: true,
          modelVersion: 'mock-v1.0',
        },
      ]

      vi.mocked(claudeDetector.detectVertebrae).mockResolvedValue({
        annotations: mockAnnotations,
        confidence: 0.9,
        processingTimeMs: 500,
      })

      const errorHandler = renderHook(() => useErrorHandler()).result.current

      // Add some existing AI annotations
      const oldAiAnnotation: MarkerAnnotation = {
        id: 'old-ai-1',
        type: 'marker',
        sopInstanceUID: mockInstance.sopInstanceUID,
        seriesInstanceUID: 'series-1',
        instanceNumber: 1,
        position: { x: 100, y: 100 },
        label: 'OLD',
        severity: 'normal',
        description: 'AI-detected marker',
        createdAt: new Date().toISOString(),
        createdBy: 'AI',
        autoGenerated: true,
        modelVersion: 'old-v1.0',
      }
      useAnnotationStore.getState().addAnnotations([oldAiAnnotation])

      const { result } = renderHook(() =>
        useAiOperations({
          currentInstance: mockInstance,
          currentStudy: mockStudy,
          isDetecting: false,
          isAnalyzing: false,
          setDetecting: vi.fn(),
          setAnalyzing: vi.fn(),
          addAnnotations: useAnnotationStore.getState().addAnnotations,
          deleteAnnotationsForInstance: useAnnotationStore.getState().deleteAnnotationsForInstance,
          addAnalysis: vi.fn(),
          handleError: errorHandler.handleError,
        })
      )

      // Run detection
      await act(async () => {
        await result.current.handleAiDetection()
      })

      // Verify detector was called
      expect(claudeDetector.detectVertebrae).toHaveBeenCalledWith(mockInstance)

      // Verify old AI annotations were deleted
      const annotations = useAnnotationStore.getState().annotations
      const oldAnnotation = annotations.find(a => a.id === 'old-ai-1')
      expect(oldAnnotation).toBeUndefined()

      // Verify new annotations were added
      const newAnnotations = annotations.filter(a => a.autoGenerated)
      expect(newAnnotations).toHaveLength(1)
      expect((newAnnotations[0] as MarkerAnnotation).label).toBe('L1')
    })

    it('should preserve manual annotations when running detection', async () => {
      const { claudeDetector } = await import('@/lib/ai/claudeVisionDetector')

      vi.mocked(claudeDetector.detectVertebrae).mockResolvedValue({
        annotations: [],
        confidence: 0.9,
        processingTimeMs: 500,
      })

      const errorHandler = renderHook(() => useErrorHandler()).result.current

      // Add manual annotation
      const manualAnnotation: MarkerAnnotation = {
        id: 'manual-1',
        type: 'marker',
        sopInstanceUID: mockInstance.sopInstanceUID,
        seriesInstanceUID: 'series-1',
        instanceNumber: 1,
        position: { x: 100, y: 100 },
        label: 'User Finding',
        severity: 'normal',
        description: 'Manual user finding',
        createdAt: new Date().toISOString(),
        createdBy: 'user',
        autoGenerated: false,
      }
      useAnnotationStore.getState().addAnnotations([manualAnnotation])

      const { result } = renderHook(() =>
        useAiOperations({
          currentInstance: mockInstance,
          currentStudy: mockStudy,
          isDetecting: false,
          isAnalyzing: false,
          setDetecting: vi.fn(),
          setAnalyzing: vi.fn(),
          addAnnotations: useAnnotationStore.getState().addAnnotations,
          deleteAnnotationsForInstance: useAnnotationStore.getState().deleteAnnotationsForInstance,
          addAnalysis: vi.fn(),
          handleError: errorHandler.handleError,
        })
      )

      // Run detection
      await act(async () => {
        await result.current.handleAiDetection()
      })

      // Verify manual annotation is still there
      const annotations = useAnnotationStore.getState().annotations
      const manualStillExists = annotations.find(a => a.id === 'manual-1')
      expect(manualStillExists).toBeDefined()
      expect(manualStillExists?.autoGenerated).toBe(false)
    })

    it('should handle detection errors gracefully', async () => {
      const { claudeDetector } = await import('@/lib/ai/claudeVisionDetector')

      vi.mocked(claudeDetector.detectVertebrae).mockRejectedValue(
        new Error('Detection failed')
      )

      const errorHandler = renderHook(() => useErrorHandler()).result.current
      const mockSetDetecting = vi.fn()

      const { result } = renderHook(() =>
        useAiOperations({
          currentInstance: mockInstance,
          currentStudy: mockStudy,
          isDetecting: false,
          isAnalyzing: false,
          setDetecting: mockSetDetecting,
          setAnalyzing: vi.fn(),
          addAnnotations: useAnnotationStore.getState().addAnnotations,
          deleteAnnotationsForInstance: useAnnotationStore.getState().deleteAnnotationsForInstance,
          addAnalysis: vi.fn(),
          handleError: errorHandler.handleError,
        })
      )

      // Run detection
      await act(async () => {
        await result.current.handleAiDetection()
      })

      // Verify detecting state was set back to false with error
      expect(mockSetDetecting).toHaveBeenLastCalledWith(false, 'Detection failed')

      // No annotations should be added
      expect(useAnnotationStore.getState().annotations).toHaveLength(0)
    })
  })

  describe('AI radiology analysis workflow', () => {
    it('should run analysis and store results', async () => {
      const { claudeDetector } = await import('@/lib/ai/claudeVisionDetector')

      const mockAnalysis: AiAnalysis = {
        id: 'analysis-1',
        sopInstanceUID: mockInstance.sopInstanceUID,
        instanceNumber: mockInstance.instanceNumber,
        findings: 'Normal brain MRI',
        createdAt: new Date().toISOString(),
        createdBy: 'claude-test',
        modelVersion: 'claude-3-opus',
      }

      vi.mocked(claudeDetector.analyzeImage).mockResolvedValue({
        analysis: mockAnalysis,
        processingTimeMs: 2000,
      })

      const errorHandler = renderHook(() => useErrorHandler()).result.current

      const { result } = renderHook(() =>
        useAiOperations({
          currentInstance: mockInstance,
          currentStudy: mockStudy,
          isDetecting: false,
          isAnalyzing: false,
          setDetecting: vi.fn(),
          setAnalyzing: vi.fn(),
          addAnnotations: vi.fn(),
          deleteAnnotationsForInstance: vi.fn(),
          addAnalysis: useAiAnalysisStore.getState().addAnalysis,
          handleError: errorHandler.handleError,
        })
      )

      // Run analysis
      await act(async () => {
        await result.current.handleAiAnalysis()
      })

      // Verify Claude was called
      expect(claudeDetector.analyzeImage).toHaveBeenCalledWith(mockInstance)

      // Verify analysis was stored
      const analyses = useAiAnalysisStore.getState().analyses
      expect(analyses).toHaveLength(1)
      expect(analyses[0].findings).toBe('Normal brain MRI')
      expect(analyses[0].studyInstanceUID).toBe(mockStudy.studyInstanceUID)
    })

    it('should not run analysis without study UID', async () => {
      const { claudeDetector } = await import('@/lib/ai/claudeVisionDetector')
      const errorHandler = renderHook(() => useErrorHandler()).result.current

      const { result } = renderHook(() =>
        useAiOperations({
          currentInstance: mockInstance,
          currentStudy: null, // No study
          isDetecting: false,
          isAnalyzing: false,
          setDetecting: vi.fn(),
          setAnalyzing: vi.fn(),
          addAnnotations: vi.fn(),
          deleteAnnotationsForInstance: vi.fn(),
          addAnalysis: vi.fn(),
          handleError: errorHandler.handleError,
        })
      )

      // Try to run analysis
      await act(async () => {
        await result.current.handleAiAnalysis()
      })

      // Claude should not have been called
      expect(claudeDetector.analyzeImage).not.toHaveBeenCalled()
    })

    it('should handle analysis errors and report to user', async () => {
      const { claudeDetector } = await import('@/lib/ai/claudeVisionDetector')

      vi.mocked(claudeDetector.analyzeImage).mockRejectedValue(
        new Error('API quota exceeded')
      )

      const mockHandleError = vi.fn()

      const { result } = renderHook(() =>
        useAiOperations({
          currentInstance: mockInstance,
          currentStudy: mockStudy,
          isDetecting: false,
          isAnalyzing: false,
          setDetecting: vi.fn(),
          setAnalyzing: vi.fn(),
          addAnnotations: vi.fn(),
          deleteAnnotationsForInstance: vi.fn(),
          addAnalysis: useAiAnalysisStore.getState().addAnalysis,
          handleError: mockHandleError,
        })
      )

      // Run analysis
      await act(async () => {
        await result.current.handleAiAnalysis()
      })

      // Verify error was handled
      expect(mockHandleError).toHaveBeenCalledWith(
        expect.objectContaining({ message: 'API quota exceeded' }),
        'AI Analysis',
        'error'
      )

      // No analysis should be stored
      expect(useAiAnalysisStore.getState().analyses).toHaveLength(0)
    })
  })

  describe('Combined detection and analysis workflow', () => {
    it('should run detection then analysis on same instance', async () => {
      const { claudeDetector } = await import('@/lib/ai/claudeVisionDetector')

      const mockAnnotations: MarkerAnnotation[] = [
        {
          id: 'ai-1',
          type: 'marker',
          sopInstanceUID: mockInstance.sopInstanceUID,
          seriesInstanceUID: 'series-1',
          instanceNumber: 1,
          position: { x: 256, y: 100 },
          label: 'L1',
          severity: 'normal',
          description: 'AI-detected marker',
          createdAt: new Date().toISOString(),
          createdBy: 'AI',
          autoGenerated: true,
          modelVersion: 'v1.0',
        },
      ]

      vi.mocked(claudeDetector.detectVertebrae).mockResolvedValue({
        annotations: mockAnnotations,
        confidence: 0.9,
        processingTimeMs: 500,
      })

      vi.mocked(claudeDetector.analyzeImage).mockResolvedValue({
        analysis: {
          id: 'analysis-1',
          sopInstanceUID: mockInstance.sopInstanceUID,
          instanceNumber: mockInstance.instanceNumber,
          findings: 'Vertebrae detected successfully',
          createdAt: new Date().toISOString(),
          createdBy: 'claude-test',
          modelVersion: 'claude-3-opus',
        },
        processingTimeMs: 2000,
      })

      const errorHandler = renderHook(() => useErrorHandler()).result.current

      const { result } = renderHook(() =>
        useAiOperations({
          currentInstance: mockInstance,
          currentStudy: mockStudy,
          isDetecting: false,
          isAnalyzing: false,
          setDetecting: vi.fn(),
          setAnalyzing: vi.fn(),
          addAnnotations: useAnnotationStore.getState().addAnnotations,
          deleteAnnotationsForInstance: useAnnotationStore.getState().deleteAnnotationsForInstance,
          addAnalysis: useAiAnalysisStore.getState().addAnalysis,
          handleError: errorHandler.handleError,
        })
      )

      // Run detection first
      await act(async () => {
        await result.current.handleAiDetection()
      })

      expect(useAnnotationStore.getState().annotations).toHaveLength(1)

      // Then run analysis
      await act(async () => {
        await result.current.handleAiAnalysis()
      })

      expect(useAiAnalysisStore.getState().analyses).toHaveLength(1)

      // Both detection and analysis results should be present
      expect((useAnnotationStore.getState().annotations[0] as MarkerAnnotation).label).toBe('L1')
      expect(useAiAnalysisStore.getState().analyses[0].findings).toBe('Vertebrae detected successfully')
    })
  })

  describe('Guard conditions', () => {
    it('should not run detection when already detecting', async () => {
      const { claudeDetector } = await import('@/lib/ai/claudeVisionDetector')
      const errorHandler = renderHook(() => useErrorHandler()).result.current

      const { result } = renderHook(() =>
        useAiOperations({
          currentInstance: mockInstance,
          currentStudy: mockStudy,
          isDetecting: true, // Already detecting
          isAnalyzing: false,
          setDetecting: vi.fn(),
          setAnalyzing: vi.fn(),
          addAnnotations: useAnnotationStore.getState().addAnnotations,
          deleteAnnotationsForInstance: useAnnotationStore.getState().deleteAnnotationsForInstance,
          addAnalysis: vi.fn(),
          handleError: errorHandler.handleError,
        })
      )

      await act(async () => {
        await result.current.handleAiDetection()
      })

      // Detector should not have been called
      expect(claudeDetector.detectVertebrae).not.toHaveBeenCalled()
    })

    it('should not run analysis when already analyzing', async () => {
      const { claudeDetector } = await import('@/lib/ai/claudeVisionDetector')
      const errorHandler = renderHook(() => useErrorHandler()).result.current

      const { result } = renderHook(() =>
        useAiOperations({
          currentInstance: mockInstance,
          currentStudy: mockStudy,
          isDetecting: false,
          isAnalyzing: true, // Already analyzing
          setDetecting: vi.fn(),
          setAnalyzing: vi.fn(),
          addAnnotations: vi.fn(),
          deleteAnnotationsForInstance: vi.fn(),
          addAnalysis: vi.fn(),
          handleError: errorHandler.handleError,
        })
      )

      await act(async () => {
        await result.current.handleAiAnalysis()
      })

      // Claude should not have been called
      expect(claudeDetector.analyzeImage).not.toHaveBeenCalled()
    })
  })
})
