/**
 * Integration tests for annotation workflow
 *
 * Tests the complete annotation lifecycle: creation, retrieval,
 * updates, filtering, and deletion.
 */

import { describe, it, expect, beforeEach } from 'vitest'
import { useAnnotationStore } from '@/stores/annotationStore'
import { useStudyStore } from '@/stores/studyStore'
import { createMockStudy, createMockInstance } from '@/test/fixtures/dicomData'
import type { MarkerAnnotation, MeasurementAnnotation } from '@/types/annotation'

describe('Annotation Workflow Integration', () => {
  let mockInstance: ReturnType<typeof createMockInstance>

  beforeEach(() => {
    localStorage.clear() // Clear view state persistence
    useAnnotationStore.getState().reset()
    useStudyStore.getState().reset()
    mockInstance = createMockInstance()
  })

  describe('Annotation creation and retrieval', () => {
    it('should create marker annotation and retrieve it', () => {
      const annotationStore = useAnnotationStore.getState()

      const marker: MarkerAnnotation = {
        id: 'marker-1',
        type: 'marker',
        sopInstanceUID: mockInstance.sopInstanceUID,
        seriesInstanceUID: 'series-1',
        instanceNumber: 1,
        position: { x: 256, y: 256 },
        label: 'L1',
        severity: 'normal',
        description: 'First lumbar vertebra',
        createdAt: new Date().toISOString(),
        createdBy: 'user',
        autoGenerated: false,
      }

      // Add annotation
      annotationStore.addAnnotations([marker])

      // Retrieve all annotations
      const allAnnotations = annotationStore.annotations
      expect(allAnnotations).toHaveLength(1)
      expect(allAnnotations[0]).toEqual(marker)

      // Retrieve annotations for this instance
      const instanceAnnotations = annotationStore.getAnnotationsForInstance(
        mockInstance.sopInstanceUID
      )
      expect(instanceAnnotations).toHaveLength(1)
      expect(instanceAnnotations[0]).toEqual(marker)
    })

    it('should create measurement annotation and calculate length', () => {
      const annotationStore = useAnnotationStore.getState()

      const measurement: MeasurementAnnotation = {
        id: 'measurement-1',
        type: 'measurement',
        sopInstanceUID: mockInstance.sopInstanceUID,
        seriesInstanceUID: 'series-1',
        instanceNumber: 1,
        points: [{ x: 100, y: 100 }, { x: 200, y: 200 }],
        measurementType: 'length',
        value: Math.sqrt(100 * 100 + 100 * 100), // ~141.42
        unit: 'px',
        severity: 'normal',
        description: 'Lesion diameter',
        createdAt: new Date().toISOString(),
        createdBy: 'user',
        autoGenerated: false,
      }

      annotationStore.addAnnotations([measurement])

      const annotations = annotationStore.annotations
      expect(annotations).toHaveLength(1)
      expect(annotations[0].type).toBe('measurement')

      const retrieved = annotations[0] as MeasurementAnnotation
      expect(retrieved.value).toBeCloseTo(141.42, 2)
    })

    it('should create multiple annotations for same instance', () => {
      const annotationStore = useAnnotationStore.getState()

      const annotations: MarkerAnnotation[] = [
        {
          id: 'marker-1',
          type: 'marker',
          sopInstanceUID: mockInstance.sopInstanceUID,
          seriesInstanceUID: 'series-1',
          instanceNumber: 1,
          position: { x: 256, y: 200 },
          label: 'L1',
          severity: 'normal',
          description: 'Test marker L1',
          createdAt: new Date().toISOString(),
          createdBy: 'user',
          autoGenerated: false,
        },
        {
          id: 'marker-2',
          type: 'marker',
          sopInstanceUID: mockInstance.sopInstanceUID,
          seriesInstanceUID: 'series-1',
          instanceNumber: 1,
          position: { x: 256, y: 250 },
          label: 'L2',
          severity: 'normal',
          description: 'Test marker L2',
          createdAt: new Date().toISOString(),
          createdBy: 'user',
          autoGenerated: false,
        },
      ]

      annotationStore.addAnnotations(annotations)

      const instanceAnnotations = annotationStore.getAnnotationsForInstance(
        mockInstance.sopInstanceUID
      )
      expect(instanceAnnotations).toHaveLength(2)
    })
  })

  describe('Annotation updates', () => {
    it('should update annotation description', () => {
      const annotationStore = useAnnotationStore.getState()

      const marker: MarkerAnnotation = {
        id: 'marker-1',
        type: 'marker',
        sopInstanceUID: mockInstance.sopInstanceUID,
        seriesInstanceUID: 'series-1',
        instanceNumber: 1,
        position: { x: 256, y: 256 },
        label: 'L1',
        severity: 'normal',
        description: 'Original description',
        createdAt: new Date().toISOString(),
        createdBy: 'user',
        autoGenerated: false,
      }

      annotationStore.addAnnotations([marker])

      // Update annotation
      const updated = {
        ...marker,
        description: 'Updated description',
      }
      annotationStore.updateAnnotation(marker.id, updated)

      const retrieved = annotationStore.annotations[0] as MarkerAnnotation
      expect(retrieved.description).toBe('Updated description')
    })

    it('should update annotation severity', () => {
      const annotationStore = useAnnotationStore.getState()

      const marker: MarkerAnnotation = {
        id: 'marker-1',
        type: 'marker',
        sopInstanceUID: mockInstance.sopInstanceUID,
        seriesInstanceUID: 'series-1',
        instanceNumber: 1,
        position: { x: 256, y: 256 },
        label: 'Finding',
        severity: 'normal',
        description: 'Test finding',
        createdAt: new Date().toISOString(),
        createdBy: 'user',
        autoGenerated: false,
      }

      annotationStore.addAnnotations([marker])

      // Update severity
      const updated = { ...marker, severity: 'warning' as const }
      annotationStore.updateAnnotation(marker.id, updated)

      const retrieved = annotationStore.annotations[0] as MarkerAnnotation
      expect(retrieved.severity).toBe('warning')
    })
  })

  describe('Annotation filtering', () => {
    beforeEach(() => {
    localStorage.clear() // Clear view state persistence
      const annotationStore = useAnnotationStore.getState()

      // Add mix of manual and AI-generated annotations
      const annotations: MarkerAnnotation[] = [
        {
          id: 'manual-1',
          type: 'marker',
          sopInstanceUID: mockInstance.sopInstanceUID,
          seriesInstanceUID: 'series-1',
          instanceNumber: 1,
          position: { x: 100, y: 100 },
          label: 'Manual 1',
          severity: 'normal',
          description: 'Manual annotation 1',
          createdAt: new Date().toISOString(),
          createdBy: 'user',
          autoGenerated: false,
        },
        {
          id: 'ai-1',
          type: 'marker',
          sopInstanceUID: mockInstance.sopInstanceUID,
          seriesInstanceUID: 'series-1',
          instanceNumber: 1,
          position: { x: 200, y: 200 },
          label: 'AI 1',
          severity: 'normal',
          description: 'AI-detected marker',
          createdAt: new Date().toISOString(),
          createdBy: 'AI-Detector',
          autoGenerated: true,
          modelVersion: 'v1.0',
        },
        {
          id: 'manual-2',
          type: 'marker',
          sopInstanceUID: 'different-instance',
          seriesInstanceUID: 'series-1',
          instanceNumber: 2,
          position: { x: 150, y: 150 },
          label: 'Manual 2',
          severity: 'normal',
          description: 'Manual annotation 2',
          createdAt: new Date().toISOString(),
          createdBy: 'user',
          autoGenerated: false,
        },
      ]

      annotationStore.addAnnotations(annotations)
    })

    it('should filter annotations by instance', () => {
      const annotationStore = useAnnotationStore.getState()

      const instanceAnnotations = annotationStore.getAnnotationsForInstance(
        mockInstance.sopInstanceUID
      )

      expect(instanceAnnotations).toHaveLength(2)
      expect(instanceAnnotations.every(a => a.sopInstanceUID === mockInstance.sopInstanceUID)).toBe(true)
    })

    it('should filter AI-generated annotations', () => {
      const annotationStore = useAnnotationStore.getState()

      const instanceAnnotations = annotationStore.getAnnotationsForInstance(
        mockInstance.sopInstanceUID
      )

      const aiAnnotations = instanceAnnotations.filter(a => a.autoGenerated)
      const manualAnnotations = instanceAnnotations.filter(a => !a.autoGenerated)

      expect(aiAnnotations).toHaveLength(1)
      expect(manualAnnotations).toHaveLength(1)
      expect(aiAnnotations[0].id).toBe('ai-1')
    })
  })

  describe('Annotation deletion', () => {
    it('should delete single annotation', () => {
      const annotationStore = useAnnotationStore.getState()

      const marker: MarkerAnnotation = {
        id: 'marker-1',
        type: 'marker',
        sopInstanceUID: mockInstance.sopInstanceUID,
        seriesInstanceUID: 'series-1',
        instanceNumber: 1,
        position: { x: 256, y: 256 },
        label: 'L1',
        severity: 'normal',
        description: 'Test marker',
        createdAt: new Date().toISOString(),
        createdBy: 'user',
        autoGenerated: false,
      }

      annotationStore.addAnnotations([marker])
      expect(annotationStore.annotations).toHaveLength(1)

      // Delete annotation
      annotationStore.deleteAnnotation(marker.id)
      expect(annotationStore.annotations).toHaveLength(0)
    })

    it('should delete all annotations for instance', () => {
      const annotationStore = useAnnotationStore.getState()

      const annotations: MarkerAnnotation[] = [
        {
          id: 'marker-1',
          type: 'marker',
          sopInstanceUID: mockInstance.sopInstanceUID,
          seriesInstanceUID: 'series-1',
          instanceNumber: 1,
          position: { x: 100, y: 100 },
          label: 'A',
          severity: 'normal',
          description: 'Test marker A',
          createdAt: new Date().toISOString(),
          createdBy: 'user',
          autoGenerated: false,
        },
        {
          id: 'marker-2',
          type: 'marker',
          sopInstanceUID: mockInstance.sopInstanceUID,
          seriesInstanceUID: 'series-1',
          instanceNumber: 1,
          position: { x: 200, y: 200 },
          label: 'B',
          severity: 'normal',
          description: 'Test marker B',
          createdAt: new Date().toISOString(),
          createdBy: 'user',
          autoGenerated: false,
        },
        {
          id: 'marker-3',
          type: 'marker',
          sopInstanceUID: 'different-instance',
          seriesInstanceUID: 'series-1',
          instanceNumber: 2,
          position: { x: 150, y: 150 },
          label: 'C',
          severity: 'normal',
          description: 'Test marker C',
          createdAt: new Date().toISOString(),
          createdBy: 'user',
          autoGenerated: false,
        },
      ]

      annotationStore.addAnnotations(annotations)
      expect(annotationStore.annotations).toHaveLength(3)

      // Delete all for first instance
      annotationStore.deleteAnnotationsForInstance(mockInstance.sopInstanceUID, false)

      const remaining = annotationStore.annotations
      expect(remaining).toHaveLength(1)
      expect(remaining[0].id).toBe('marker-3')
    })

    it('should delete only AI annotations when autoOnly is true', () => {
      const annotationStore = useAnnotationStore.getState()

      const annotations: MarkerAnnotation[] = [
        {
          id: 'manual-1',
          type: 'marker',
          sopInstanceUID: mockInstance.sopInstanceUID,
          seriesInstanceUID: 'series-1',
          instanceNumber: 1,
          position: { x: 100, y: 100 },
          label: 'Manual',
          severity: 'normal',
          description: 'Manual annotation',
          createdAt: new Date().toISOString(),
          createdBy: 'user',
          autoGenerated: false,
        },
        {
          id: 'ai-1',
          type: 'marker',
          sopInstanceUID: mockInstance.sopInstanceUID,
          seriesInstanceUID: 'series-1',
          instanceNumber: 1,
          position: { x: 200, y: 200 },
          label: 'AI',
          severity: 'normal',
          description: 'AI-detected marker',
          createdAt: new Date().toISOString(),
          createdBy: 'AI',
          autoGenerated: true,
          modelVersion: 'v1.0',
        },
      ]

      annotationStore.addAnnotations(annotations)
      expect(annotationStore.annotations).toHaveLength(2)

      // Delete only AI annotations
      annotationStore.deleteAnnotationsForInstance(mockInstance.sopInstanceUID, true)

      const remaining = annotationStore.annotations
      expect(remaining).toHaveLength(1)
      expect(remaining[0].id).toBe('manual-1')
      expect(remaining[0].autoGenerated).toBe(false)
    })
  })

  describe('Integration with study workflow', () => {
    it('should manage annotations across multiple instances in a series', () => {
      const mockStudy = createMockStudy(1, 3) // 1 series, 3 instances
      const studyStore = useStudyStore.getState()
      const annotationStore = useAnnotationStore.getState()

      studyStore.setStudies([mockStudy])
      studyStore.setCurrentStudy(mockStudy.studyInstanceUID)

      const series = mockStudy.series[0]

      // Add annotations to each instance
      const annotations: MarkerAnnotation[] = series.instances.map((instance, i) => ({
        id: `marker-${i}`,
        type: 'marker',
        sopInstanceUID: instance.sopInstanceUID,
        seriesInstanceUID: series.seriesInstanceUID,
        instanceNumber: instance.instanceNumber,
        position: { x: 100 + i * 50, y: 100 + i * 50 },
        label: `L${i + 1}`,
        severity: 'normal',
        description: `Test marker L${i + 1}`,
        createdAt: new Date().toISOString(),
        createdBy: 'user',
        autoGenerated: false,
      }))

      annotationStore.addAnnotations(annotations)

      // Verify each instance has its annotation
      series.instances.forEach(instance => {
        const instanceAnnotations = annotationStore.getAnnotationsForInstance(
          instance.sopInstanceUID
        )
        expect(instanceAnnotations).toHaveLength(1)
      })

      // Total annotations should be 3
      expect(annotationStore.annotations).toHaveLength(3)
    })
  })
})
